projects: *projects
  target: auto
  threshold: 1%
  if_ci_failed: error
  if_not_found: success
patch: *patch
  only_pulls: true
  target: auto
  threshold: 10%
  if_ci_failed: error
  if_not_found: failure

codecov:
  allow_coverage_offsets: true

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default: false
      linux-1.13:
        <<: *projects
        flags:
          - "linux-1.14"
      linux-1.14:
        <<: *projects
        flags:
          - "linux-1.15"
      linux-1.15:
        <<: *projects
        flags:
          - "linux-1.16"
      macos-1.13:
        <<: *projects
        flags:
          - "macos-1.14"
      macos-1.14:
        <<: *projects
        flags:
          - "macos-1.15"
      macos-1.15:
        <<: *projects
        flags:
          - "macos-1.16"
      windows-1.13:
        <<: *projects
        flags:
          - "windows-1.14"
      windows-1.14:
        <<: *projects
        flags:
          - "windows-1.15"
      windows-1.15:
        <<: *projects
        flags:
          - "windows-1.16"
    patch:
      default: false
      linux-1.13:
        <<: *patch
      linux-1.14:
        <<: *patch
      linux-1.15:
        <<: *patch
      macos-1.13:
        <<: *patch
      macos-1.14:
        <<: *patch
      macos-1.15:
        <<: *patch
      windows-1.13:
        <<: *patch
      windows-1.14:
        <<: *patch
      windows-1.15:
        <<: *patch
    changes:
      default:
        if_ci_failed: error
        if_not_found: success
        only_pulls: false
        branches:
          - master
        flags:
          - "linux-1.14"
          - "linux-1.15"
          - "linux-1.16"
          - "macos-1.14"
          - "macos-1.15"
          - "macos-1.16"
          - "windows-1.14"
          - "windows-1.15"
          - "windows-1.16"

flags:
  linux-1.14:
    paths:
      - /
    carryforward: true
  linux-1.15:
    paths:
      - /
    carryforward: true
  linux-1.16:
    paths:
      - /
    carryforward: true
  macos-1.14:
    paths:
      - /
    carryforward: true
  macos-1.15:
    paths:
      - /
    carryforward: true
  macos-1.16:
    paths:
      - /
    carryforward: true
  windows-1.14:
    paths:
      - /
    carryforward: true
  windows-1.15:
    paths:
      - /
    carryforward: true
  windows-1.16:
    paths:
      - /
    carryforward: true

comment:
  behavior: default
  require_changes: true

github_checks:
  annotations: true
